spring:
  application:
    name: learn-graphql-kotlin

server:
  http2:
    enabled: true

graphql:
  servlet:
    max-query-depth: 100
    tracing-enabled: true
    exception-handlers-enabled: true

  playground:
    headers:
      Authorization: Bearer TOKEN
      user_id: idp|jerry
      # security test 시에는 이 부분 빼고 실행해볼 것
      user_roles : "get:bank_account,get:bank_account_balance"
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_vatiables.json

voyager:
  enabled: true
